version: '3'

services:
  backend-service:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/usr/src/backend
  
  frontend-service:
    build: ./frontend
    ports:
      - "8000:80"
    volumes:
      - ./frontend:/usr/src/frontend

